Quote.delete_all
Author.delete_all
Topic.delete_all

# TOPICS
knowledge = Topic.create(name: "Knowledge")
wisdom = Topic.create(name: "Integrity")
compromise = Topic.create(name: "Compromise")
improvement = Topic.create(name: "Self-improvement")
success = Topic.create(name: "Success")
moderation = Topic.create(name: "Moderation")
stoicism = Topic.create(name: "Stoicism")
justice = Topic.create(name: "Justice")
freedom = Topic.create(name: "Freedom")
finances = Topic.create(name: "Finances")
startups = Topic.create(name: "Startups")
humor = Topic.create(name: "Humor")
failure = Topic.create(name: "Failure")
growth_t = Topic.create(name: "Growth")
communication = Topic.create(name: "Communication")
regret = Topic.create(name: "Regret")
death = Topic.create(name: "Death")
maturity = Topic.create(name: "Maturity")
service = Topic.create(name: "Service")
appearance = Topic.create(name: "Appearance")
democracy = Topic.create(name: "Democracy")
planning = Topic.create(name: "Planning")

# AUTHORS
thanos = Author.create(name: "Thanos")
socrates = Author.create(name: "Socrates")
lincoln = Author.create(name: "Abraham Lincoln")
carrel = Author.create(name: "Alexis Carrel")
branko = Author.create(name: "Branko Backovic")
democritus = Author.create(name: "Democritus")
seneca = Author.create(name: "Seneca")
plato = Author.create(name: "Plato")
edmylett = Author.create(name: "Ed Mylett")
thiel = Author.create(name: "Peter Thiel")
denzelw = Author.create(name: "Denzel Washington")
unknown = Author.create(name: "Unknown")
swordandpencil = Author.create(name: "Sword and Pencil")
musk = Author.create(name: "Elon Musk")
kendrick = Author.create(name: "Kendrick Lamar")
malc = Author.create(name: "Malcolm Keyes")
cervantes = Author.create(name: "Miguel de Cervantes")

# QUOTES
cursed = Quote.create(message: "You're not the only one cursed with knowledge", author: thanos, topics: [knowledge, regret], source: "Avengers: Infinity War", year: 2018, url: "https://www.youtube.com/watch?v=upJpEKUnJlg&ab_channel=Pung5252")
wickedness = Quote.create(message: "It is not difficult to avoid death, gentlemen; it is much more difficult to avoid wickedness, for it runs faster than death.", author: socrates, topics: [wisdom, death], source: "The Apology", year: -399)
right = Quote.create(message: "If both factions, or neither, shall abuse you, you will probably be about right. Beware of being assailed by one and praised by the other.", author: lincoln, topics: [compromise], year: 1863, source: "Letter to General J. M. Schofield", url: "http://www.perseus.tufts.edu/hopper/text?doc=Perseus%3Atext%3A2001.05.0131%3Achapter%3D5%3Apage%3D69")
marble = Quote.create(message: "To progress again, man must remake himself. And he cannot remake himself without suffering. For he is both the marble and the sculptor. In order to uncover his true visage he must shatter his own substance with heavy blows of his hammer.", author: carrel, topics: [improvement, growth_t], year: 1935, source: "Man, the Unknown", url: "https://www.reddit.com/r/QuotesPorn/comments/1fkjkq/man_cannot_remake_himself_without_suffering_for/") # If you know the author of this quote, this quote is actually pretty unsettling, but the quote - without the context of the author - really is great
journey = Quote.create(message: "You meet the same people on the way up as you do on the way down.", author: branko, topics: [success], year: 2022)
occassion = Quote.create(message: "Thrift and fasting are good: so too is extravagance on occasion: it is the mark of a good man to recognize the occasion", author: democritus, topics: [moderation, maturity], year: -400)
overindulgence = Quote.create(message: "If you exceed the measure, what is most enjoyable becomes least enjoyable.", author: democritus, topics: [moderation], year: -400)
duty = Quote.create(message: "The duty of a man is to be useful to his fellow-men; if possible, to be useful to many of them; failing this, to be useful to a few; failing this, to be useful to his neighbours, and, failing them, to himself: for when he helps others, he advances the general interests of mankind. Just as he who makes himself a worse man does harm not only to himself but to all those to whom he might have done good if he had made himself a better one, so he who deserves well of himself does good to others by the very fact that he is preparing what will be of service to them.", author: seneca, topics: [stoicism, service], source: "On Leisure", year: 62)
appearance = Quote.create(message: "Can I by justice or by crooked ways of deceit ascend a loftier tower which may he a fortress to me all my days? For what men say is that, if I am really just and am not also thought just profit there is none, but the pain and loss on the other hand are unmistakable. But if, though unjust, I acquire the reputation of justice, a heavenly life is promised to me. Since then, as philosophers prove, appearance tyrannizes over truth and is lord of happiness, to appearance I must devote myself.", author: plato, topics: [justice, appearance], source: "The Republic: Book II", year: -380)
democracy = Quote.create(message: "Poverty in a democracy is preferable to what is called prosperity among tyrants - by as much liberty is preferable to slavery.", author: democritus, topics: [freedom, democracy], year: -400)
spending = Quote.create(message: "Don't go broke trying to look rich. If you don't save when you're poor...the crazy belief system is that you'll start saving when you start making money. If you have a habit of spending, you'll spend more when you make more.", author: edmylett, topics: [finances], year: 2019, source: "Interview with Tom Bilyeu")
scale = Quote.create(message: "A good startup should have the potential for great scale built into its first design.",topics: [startups, success], author: thiel, year: 2014, source: "Zero to One: Notes on Startups, or How to Build the Future")
dreams = Quote.create(message: "Dreams without goals are just dreams - and they ultimately fuel disappointment.", author: denzelw, topics: [success, planning], year: 2014, source: "Advice to young actors, Broadway Cares/Equity Fights AIDS Easter Bonnet Competition")
backseat = Quote.create(message: "Kids in the back seat may cause accidents... Accidents in the back seat may cause kids... No back seat = No accidents", topics: [humor], author: unknown)
growth = Quote.create(message: "Growth requires a death.", author: swordandpencil, year: 2022, topics: [growth_t, death])
option = Quote.create(message: "Failure is an option here. If things are not failing, you are not innovating enough.", author: musk, topics: [failure, success], year: 2005, source: "Interview with Fast Company")
crown = Quote.create(message: "The closest ones afraid to say they need some time / The turn around is life or death, but you don't mind", author: kendrick, topics: [communication], year: 2022, source: "'Crown' off of Mr.Morale & The Big Steppers")
moves = Quote.create(message: "All my moves are big moves. I am overweight.", author: malc, topics: [humor], year: 2022)
reading = Quote.create(message: "El que lee mucho y anda mucho, ve mucho y sabe mucho.", author: cervantes, year: 1605, topics: [knowledge], source: "Don Quijote de la Mancha")
